name: "Promotes dev environment tag to test environment"
on:
  workflow_call:
    inputs:
      repository-name: 
        description: "El nombre del repositorio"
        required: true
        type: string

    secrets:
        PAT:
          description: "Personal Access Token para acceder al repositorio de manifiestos"
          required: true
jobs:


  docker:
    name: Build Docker image and push to Docker Hub
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ inputs.repository-name }}

    steps:
      - name: Checkout to Manifests Repo
        uses: actions/checkout@v3
        with:
          repository: 'Equipo-dinamita-escuadron-lobo/manifests-repo'
          ref: 'main'
          token: ${{ secrets.PAT }}
      - name: Setup Git Config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "<>"

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r ./scripts/requirements.txt

      - name: Promote Dev Image Tag to Test Environment
        run: python ./scripts/promote.py -s ./environments/dev/values-${{ env.REPO_NAME }}.yaml -d ./environments/test/values-${{ env.REPO_NAME }}.yaml

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Promoted image tag of ${{env.REPO_NAME }}"
          git push
